controllers:
  main:
    # hostNetwork: true is the equivalent of network_mode: host
    # hostNetwork: true
    # # Since we are using hostNetwork, we don't need a traditional service, 
    # # but keep this if you want to be able to monitor the pod internally.
    # type: deployment
    containers:
      main:
        tty: true        # <-- add this
        image:
          repository: lshallo/ats-convoy-server
          tag: "{{.Chart.AppVersion}}"
        env:
          ETS_SERVER_UPDATE_ON_START: "true"
          ETS_SERVER_NAME: "sixseventrucking"
          ETS_SERVER_DESCRIPTION: "Powered by K8s"
          ETS_SERVER_WELCOME_MESSAGE: "Welcome to winter hell! Powered by K8s"
          ETS_SERVER_MAX_PLAYERS: "4"
          ETS_SERVER_PORT: "27015"
          ETS_SERVER_QUERY_PORT: "27016"
          ETS_SERVER_MODS_OPTIONING: "true"
          ETS_SERVER_PLAYER_DAMAGE: "true"
          ETS_SERVER_TRAFFIC: "true"
          ETS_SERVER_SERVICE_NO_COLLISION: "false"
          ETS_SERVER_HIDE_COLLIDING: "false"
          ETS_SERVER_WRITE_CONFIG: "true"
        envFrom:
          - secretRef:
              name: ats-secrets
        ports:
          - name: game-udp
            containerPort: 27015
            protocol: UDP
          - name: game-tcp
            containerPort: 27015
            protocol: TCP
          - name: query
            containerPort: 27016
            protocol: UDP

persistence:
  game-data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    # existingClaim: ats-game-data-pvc
    globalMounts:
      - path: /app
  save-data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 3Gi
    # existingClaim: ats-save-data-pvc
    globalMounts:
      - path: /home/steam/.local/share/American Truck Simulator