apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/immich
  - immich-sealed-secret.yaml
  - ./database
  - ./storage
configMapGenerator:
  - name: immich-values
    namespace: default
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true