persistence:
  photography:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: octapool-photography-library-pvc
    globalMounts:
      - path: /mnt/octapool-photography
        readOnly: true

  images:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: octapool-images-library-pvc
    globalMounts:
      - path: /mnt/octapool-images
        readOnly: true

controllers:
  main:
    containers:
      main:
        env:
          DB_HOSTNAME: immich-db
        envFrom:
          - secretRef:
              name: immich-secrets

valkey:
  enabled: true

server:
  enabled: true
  ingress:
    main:
      enabled: true
      className: traefik
      hosts:
        - host: immich.mistyfumes.dev
          paths:
            - path: "/"
              service:
                identifier: main
      tls:
        - secretName: prod-mistyfumes-tls
          hosts:
            - immich.mistyfumes.dev
