---
controllers:
  main:
    containers:
      main:
        env:
          DATA_FOLDER: /data
        image:
          repository: deluan/navidrome
          tag: "0.62.0"
    strategy: Recreate

ingress:
  main:
    className: traefik
    hosts:
    - host: navidrome.mistyfumes.dev
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: main
          port: http
    tls:
    - hosts:
      - navidrome.mistyfumes.dev
      secretName: prod-mistyfumes-tls

persistence:
  data:
    accessMode: ReadWriteOnce
    globalMounts:
    - path: /data
    size: 1Gi
    type: persistentVolumeClaim

  octapool-music:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: octapool-music-library-pvc
    advancedMounts:
      main:
        main:
        - path: /music

service:
  main:
    controller: main
    ports:
      http:
        port: 4533
