---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gamebot-secrets
  namespace: default
spec:
  encryptedData:
    TOKEN: AgBqtjhPkUjeRegGYFq7oXGCQ4lADaMkdNL4Av9poPiglCADN4hxuJb+d5ri0dH5aJAtRa2mtGiY3WB+yB20cMZQyZz5NwVUb9952VLQLyxL2iU1a/3f1herfhO5nHNm1ILM+snAeBAHGWPosmmZCW7CwvvhkkxpDSB4PlREvHmiPgW6CiKD56e4NSH38XEexCArJpf9FIffBMuX5pNGW/9aRqXvvHlur5JBFav4XObnVL1P8cI2l+wzlxZAkmJ/Wqw9Lfsc2YmoHl95ViBxsvuXdb53W0xFWettAgdDJUgsqEJOsiVMEZJJy+iIMDGfofUxkqZ6455+gt2Yap30gXMVgVyBGG6RBBmoJnHkx1vGen+9IrQHWWRud9IZrFq4SpV1HBXAEd+GCn4mqgvPV+YDFHH4VWB6L1U6pq8B6aIAXbMpesFuesAggVSU6FUhqMJDmPC/6CY1vzwwsh7vp+Zc9plocBXAx9aoyldk3CKYKkZq+1JOA5PmRP/3Zb0IgkRBXspHMnNxrnLBN/FTZ4d2/fCs3aEF813i1NGUb6/OAenzPLzRlBvyoEgUQEnGnQ4er3HmkIZWVa2lnaISxe4Dqmx5QTPA5LHnK+UYR4+Ph0HRAd5zVFOgLrwKqKBzOtf3EUzIWsXMFSbUfikfvvBhA/jtzFpFsJZ1e442HAVkY7izmMG4xSdcDoVzrxNx+bCpHQ7Nu3MO4FgKNoy/ozyJzhb/7P9nr2IDkZYWTDCeSdGwD6gNVGWtJpwW096CiIsm7ywWX4PxcdQLPt/AKKDvR+1HVGfWzyY=
  template:
    metadata:
      name: gamebot-secrets
      namespace: default
