apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - octapool-images-pvc.yaml
  # - octapool-photography-pvc.yaml
  - octapool-video-bluray-pv.yaml
  - octapool-video-dvds-pv.yaml
  - octapool-video-tv-pv.yaml