apiVersion: v1
kind: PersistentVolume
metadata:
  name: octapool-video-tv-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - addr=192.168.1.130
  nfs:
    server: 192.168.1.130
    path: /mnt/octaPool/video/tv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octapool-video-tv-pvc
  namespace: development
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: octapool-video-tv-pv