---
extends: default

ignore: |
  infrastructure/controllers/base/kubevirt/kubevirt-operator.yaml

rules:
  new-line-at-end-of-file: enable
  document-start: disable
  line-length: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
