apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: default
  chart:
    spec:
      chart: ./infrastructure/charts/it-tools
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom: []