apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: default
data:
  RENOVATE_AUTODISCOVER: "true"
  RENOVATE_ENDPOINT: https://code.mistyfumes.dev/api/v1
  RENOVATE_PLATFORM: gitea
  RENOVATE_GIT_AUTHOR: "Renovate Bot <renovate-bot@example.com>"
  LOG_LEVEL: debug