---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secrets
  namespace: default
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgCgwJ+gZVQF+lC52vcSpM2eLsKwJW2MzbpBhdl/iNbzGQo80Wc9VwRMcEvVYvzVtB2NcbuhdZ0r6cv0ILwZK/z8wA6Qny39zZgy7rIFVzFVwhMwuTh5Est5KxfhFBvKNELeyp0UMp/hOjYiAi9XEFCNV8YKrbIp145k+cHwqVufgo77jfXzM21HNsLWN+DzudODbfOMhTyXXq3kbOsB5k2NJdUEw+QWPbIKpwKA3DYCxXMKKX0idkkf1wRcTvcYp6SSecyIBz0rsTekc7ZvG9W6S1725nyZ8cUqYfK/kcRVs8u6FHwbIHIVdwclpp0NrUMdQHqiP34dbOzbzkbisMUNLsEoRV7Qp2dFoL9Z/Po4nT6HN3owGpDX6d0glwtWx5Ny3jNpyEZM2D79UlCZNrd7Fom2qrYrlcr2ECdwSLbGkkA/InuKgGte5IbyU3BMv3pNKf5jPcfQJdfCup8odE3RPYkChHYBtpLJ3b/z698JEQaqU7R9bogii8gNy4SfV2zKUFqL4P2CgWnsTLvpX3+bJqBT3gdMad2JDXL/Z0/7EgtUylabhkHv68iBX1mLSbGY30apoEqAEvPxih4mPemo5iGBWMSzy5iJyE0KcfFEuf2uvIbD3Ey+erqzrr5ZGahB+ArJQhihB+AAaXQwZlDNP7SyCtf9W6TvVPRkCcUz7yLLGmmORbmLevqwwOhAB/+00ewJ/+PTWgUzY/KR1LAk1H7lHAoFYQgzsXS0WaVQlYccOY5O5u1r
    RENOVATE_TOKEN: AgBwkIBSa2yfn0gFLWg4ZTTASJUqRLiRpUB6etFpr0tVX5kfVhmwNgb7K9WcT8dUbDTC/SS+xU090mrLFYryp3zlrUzrJIjax+lKjg3y8d5a8WVFchlfAPANfAZAdRlU10wvzfmpyb35qlJsMB678UneY/wNRa8E7Qzu8MshyN5K3IPnRjC+XAl1YjdSlltsLfp9xRvTjGT/2dO1w6hW2MigrNB+z/I9yoEqNEUBK7AoDBxbasz2z8G5nY97qTT30elN7tDwviD1iT74qaGK3FoCK2N+060M6NC5rbBxSVY8Ei+m0RYDkDSIc1zN95KH+l26h2KvuO0obriyD6vR1stP9nJN2Fqjiav0kz3GyYeL2TG6Kw3NYAHzIBJ+SkDEHqZ82YvvFfDv+1qt6xwt1gzM8oEaASWMlvNyiYhtxpQizLVlOJB88lEmnbKrTDjRZuQDRcW+XX4e2IyVPdvByB9+phcUHVyszWOCkvq3de81QYSvKcK8irFq41kVldIsiVegohhFeFLMu+Se8KdZgpIYdcPBOShqUE8zCDxb932cVubqq0oKRxZXvkIJfNldWZBPYHiqI3ed2fZCmJ+uMH2seF54AXbnWbBB37kXdGLTu1v5oHOk/4UWFB+WEI6Lyij1MUM1WXLXNpZcsKrLgjHP9ZlZ/BFDZoLtXH6/buKG2oYJM2ueDDQocvj0a5ahlVqjlRS+8R3zYKeUi+YLnC3WaWfj4c9Hj5tRb/nAvhtnfbdhNmmoeAnz
  template:
    metadata:
      name: renovate-secrets
      namespace: default
