controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/foldergram/foldergram
          tag: "1.1.0"
    strategy: Recreate

ingress:
  main:
    className: traefik
    hosts:
    - host: foldergram.mistyfumes.dev
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: main
          port: http
    tls:
    - hosts:
      - foldergram.mistyfumes.dev
      secretName: prod-mistyfumes-tls

service:
  main:
    controller: main
    ports:
      http:
        port: 4141

configMaps:
  app-config:
    data:
      IMAGE_DETAIL_SOURCE: "preview"
      DERIVATIVE_MODE: "eager"
      NODE_ENV: "production"
      PUBLIC_DEMO_MODE: "0"
      CSRF_TRUSTED_ORIGINS: "https://foldergram.dev.mistyfumes.dev"

persistence:
  db:
    type: persistentVolumeClaim
    existingClaim: foldergram-db
    globalMounts:
      - path: /app/data/db
  
  gallery:
    type: persistentVolumeClaim
    existingClaim: foldergram-gallery
    globalMounts:
      - path: /app/data/gallery

  thumbnails:
    type: persistentVolumeClaim
    existingClaim: foldergram-gallery
    globalMounts:
      - path: /app/data/thumbnails

  previews:
    type: persistentVolumeClaim
    existingClaim: foldergram-gallery
    globalMounts:
      - path: /app/data/previews
