services:
  drawio:
    container_name: drawio
    image: jgraph/drawio:29.6.5@sha256:80cd09f2ae4bf92579e1512de7c382ee1ba26cd529a666f5e940fb17d01becd3
    # ports:
    #   - 8080:8080
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawio-insecure.rule=Host(`drawio.mistyfumes.dev`)"
      - "traefik.http.routers.drawio-insecure.entrypoints=http"
      - "traefik.http.routers.drawio-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.drawio-secure.rule=Host(`drawio.mistyfumes.dev`)"
      - "traefik.http.routers.drawio-secure.entrypoints=https"
      - "traefik.http.routers.drawio-secure.tls=true"
      - "traefik.http.routers.drawio-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.drawio.loadbalancer.server.port=8080"
    networks: 
      - frontend

networks:
  frontend:
    external: true