controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/lukegus/termix
          tag: "release-2.3.2"
    strategy: Recreate

ingress:
  main:
    className: traefik
    hosts:
    - host: termix.mistyfumes.dev
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: main
          port: http
    tls:
    - hosts:
      - termix.mistyfumes.dev
      secretName: prod-mistyfumes-tls

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

persistence:
  data:
    type: persistentVolumeClaim
    existingClaim: termix-ssh-nfs-pvc
    globalMounts:
      - path: /app/data
