# Default values for my-termix-ssh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: traefik
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: termix.mistyfumes.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: prod-mistyfumes-tls
      hosts:
        - termix.mistyfumes.dev

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes:
  - name: termix-ssh-data
    persistentVolumeClaim:
      claimName: termix-ssh-nfs-pvc

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: termix-ssh-data
    mountPath: /app/data