name: renovate

on:
  workflow_dispatch: # allows the workflow to be run manually when desired
    branches:
      - main
  schedule: # runs this workflow at the scheduled time (uses UTC, adjust for your timezone)
    - cron: "0 12 * * *"
  # push: # runs this workflow when pushes to the main branch are made
  #   branches:
  #     - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:latest
    steps:
      - uses: actions/checkout@v4
      - run: renovate
        env:
          RENOVATE_CONFIG_FILE: ${{ gitea.workspace }}/config.js
          LOG_LEVEL: "debug"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_TOKEN }} # optional