apiVersion: v2
name: drawio
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "30.0.4"

dependencies:
  - name: app-template
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1