apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drawio
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: default
  chart:
    spec:
      chart: ./infrastructure/charts/drawio
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: drawio-values
      valuesKey: values.yaml