apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - truenas-sealed-secret.yaml
  - ../../base/democratic-csi
configMapGenerator:
  - name: csi-iscsi-values
    files:
      - truenas-api-iscsi.yaml
    options:
      disableNameSuffixHash: true
patches:
  - patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
          - kind: ConfigMap
            name: csi-iscsi-values
            valuesKey: truenas-api-iscsi.yaml
    target:
      kind: HelmRelease
      name: csi-driver-iscsi