---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-api-key
  namespace: storage
spec:
  encryptedData:
    TRUENAS_API_KEY: AgBp3yAYn2lsE7U3oNk6mw91MfgpQhGoYDBLdzVQOPyz+cTQII3cZz37rLfVUcsSdCyWyf1FFzm0p0uKgPKCmlZLMvpDMEaCMm4csQwdmcPE3GEqMCzbSy47AlxOvVy26H5XXDUhuVcrw3u1FIsrN0epUPH8UB0nOa5OcRjHzBzQXIoBtRgl9MJbTpW1UNCacH68oEElPbrKyrmN04WUGi6LQGYI1cpHqu/eVAY4ezwazTcyFcwyEFcsro93u/VHoo17Da9ip/tUD7o9unxrEtmrsRPTXOfYp7KrNsiRQkmGGwAc2CwxjleVfvY18aHx6mTFe8bj45gZGDLQUc5hmcgogZrQhAaGaaR8MqPPxHLFPpuOFG0LUqH0H6cwS3Vtii5lbn99845Cq2mvJ/IAdLkA3ccle2fHJ24xurAgdifcnwvdSSDRC4L8cD0jfj4tvNn+tl87S+4NBQ5HSzqjCHTA+VsqHI3DwRHiWIMyYkuekwYLTsph5fUZ9anMMxwQCP7Qz78wjD0N7lgkC4FoBTCY3X+FfCw0z/gmW2Q6XIoyhh3SWBCaVPbDF4KavkVEG0pIUUYkOoY7+f6LZIzmsV1jids4jBmZoadPxfcqzfixuS6UdNzphB1lWj1D6jfl/NPjmx96hDm2551IlLSM2IQMWkBPRl3yXrEm58ed4Otmg31PhgI3gLy4kMjdKGzvRopvvepOW0wvZv9QbHnYVbx6PgMETsvxE72eiCYFWNiYaMp5QspbymyVmKwPNzKKGMB1LIfRQZ6JC3pPi8Q66mk04Zc=
  template:
    metadata:
      name: truenas-api-key
      namespace: storage
    type: Opaque
