services:
  metube:
    image: alexta69/metube:2026.03.21@sha256:afd3fa2b229e3e6d4c8750618fe148af33a1f70b32af4441ecbd2d08f29d8221
    container_name: metube
    restart: unless-stopped
    # ports:
    #   - 8081:8081
    volumes:
      - /mnt/docker-nfs/volumes/metube-downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metube-insecure.rule=Host(`metube.mistyfumes.dev`)"
      - "traefik.http.routers.metube-insecure.entrypoints=http"
      - "traefik.http.routers.metube-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.metube-secure.rule=Host(`metube.mistyfumes.dev`)"
      - "traefik.http.routers.metube-secure.entrypoints=https"
      - "traefik.http.routers.metube-secure.tls=true"
      - "traefik.http.routers.metube-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"
    networks:
      - frontend

networks:
  frontend:
    external: true