apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaneo-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaneo-api
  template:
    metadata:
      labels:
        app: kaneo-api
    spec:
      containers:
        - name: kaneo-api
          image: ghcr.io/usekaneo/api:2.5.2@sha256:525733a0edf941a95875df292e41d2ced5b9ea08813e75b7f3ef78277823def7
          ports:
            - containerPort: 1337
          env:
            - name: KANEO_API_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_API_URL
            - name: KANEO_CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_CLIENT_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: kaneo-secrets
                  key: DATABASE_URL
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: kaneo-secrets
                  key: AUTH_SECRET