apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaneo-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaneo-web
  template:
    metadata:
      labels:
        app: kaneo-web
    spec:
      containers:
        - name: kaneo-web
          image: ghcr.io/usekaneo/web:2.5.3@sha256:ba70a288dd6c7f96865b748bf37724261b32f3d97aec597ac8a7553871a19195
          ports:
            - containerPort: 5173
          env:
            - name: KANEO_CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_CLIENT_URL
            - name: KANEO_API_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_API_URL