apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaneo-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaneo-web
  template:
    metadata:
      labels:
        app: kaneo-web
    spec:
      containers:
        - name: kaneo-web
          image: ghcr.io/usekaneo/web:2.5.2@sha256:e454c7fcdff839bc5477d45d533418bddb282b3c179674b35bd3d6bb0099285e
          ports:
            - containerPort: 5173
          env:
            - name: KANEO_CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_CLIENT_URL
            - name: KANEO_API_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_API_URL