apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaneo-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaneo-api
  template:
    metadata:
      labels:
        app: kaneo-api
    spec:
      containers:
        - name: kaneo-api
          image: ghcr.io/usekaneo/api:2.5.3@sha256:65180c62a5d9fde5288968ab241ee547b48d8a5766bc5187a26d9040d756aa84
          ports:
            - containerPort: 1337
          env:
            - name: KANEO_API_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_API_URL
            - name: KANEO_CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_CLIENT_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: kaneo-secrets
                  key: DATABASE_URL
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: kaneo-secrets
                  key: AUTH_SECRET