apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaneo-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaneo-web
  template:
    metadata:
      labels:
        app: kaneo-web
    spec:
      containers:
        - name: kaneo-web
          image: ghcr.io/usekaneo/web:2.7.2@sha256:7d0114a46a2e32bf1e0ccff2b5de6b2f8f413d02adbed09b043893284b38b2f5
          ports:
            - containerPort: 5173
          env:
            - name: KANEO_CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_CLIENT_URL
            - name: KANEO_API_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_API_URL