apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actualbudget
  - authentik
  - bytestash
  - drawio
  - homepage
  - immich
  - it-tools
  - jellyfin
  - kaneo
  - linkwarden
  - metube
  - termix-ssh