apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default  # <--- Flux was looking for this!
resources:
  - homepage-configmap.yaml
  - homepage-deployment.yaml
  - homepage-ingress.yaml
  - homepage-pvc.yaml
  - homepage-sealed-secret.yaml
  - homepage-svc.yaml