services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - /mnt/docker-nfs/volumes/kaneo-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaneo -d kaneo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  api:
    image: ghcr.io/usekaneo/api:2.5.2@sha256:525733a0edf941a95875df292e41d2ced5b9ea08813e75b7f3ef78277823def7
    ports:
      - 1337:1337
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default

  web:
    image: ghcr.io/usekaneo/web:2.5.2@sha256:e454c7fcdff839bc5477d45d533418bddb282b3c179674b35bd3d6bb0099285e
    ports:
      - 5173:5173
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.kaneo-insecure.rule=Host(`kaneo.mistyfumes.dev`)
      - traefik.http.routers.kaneo-insecure.entrypoints=http
      - traefik.http.routers.kaneo-insecure.middlewares=https-redirect@file
      - traefik.http.routers.kaneo-secure.rule=Host(`kaneo.mistyfumes.dev`)
      - traefik.http.routers.kaneo-secure.entrypoints=https
      - traefik.http.routers.kaneo-secure.tls=true
      - traefik.http.routers.kaneo-secure.tls.certresolver=cloudflare
      - traefik.http.services.kaneo.loadbalancer.server.port=5173
    networks:
      - default
      - frontend

networks:
  frontend:
    external: true