global:
  image:
    repository: ghcr.io/goauthentik/server
    tag: "2025.12.3"
    pullPolicy: IfNotPresent

  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: "prod-authentik-postgresql"
    - name: AUTHENTIK_POSTGRESQL__USER
      value: "authentik"
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: "authentik"
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: "authentik-secrets"
          key: "secret_key"
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: "authentik-secrets"
          key: "DB_PASS"

authentik:
  existingSecret:
    secretName: "authentik-secrets"

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - authentik.mistyfumes.dev
    tls:
      - secretName: prod-mistyfumes-tls
        hosts:
          - authentik.mistyfumes.dev

postgresql:
  enabled: false