global:
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: "authentik-postgresql"
    - name: AUTHENTIK_POSTGRESQL__USER
      value: "authentik"
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: "authentik"
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: "authentik-secrets"
          key: "secret_key"
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: "authentik-secrets"
          key: "DB_PASS"

authentik:
  existingSecret:
    secretName: "authentik-secrets"

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - authentik.mistyfumes.dev
    tls:
      - secretName: prod-mistyfumes-tls
        hosts:
          - authentik.mistyfumes.dev
  resources:
    limits:
      cpu: 500m      # Prevents the server from hogging the CPU
      memory: 1Gi  # Prevents OOM kills
    requests:
      cpu: 100m
      memory: 256Mi

worker:
  resources:
    limits:
      cpu: 500m      # Crucial: This limits the "heavy lifting" tasks
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 384Mi


postgresql:
  enabled: false
