apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
  - ../../base/drawio
configMapGenerator:
  - name: drawio-values
    files:
      - values.yaml=dev-values.yaml
    options:
      disableNameSuffixHash: true
patches:
  - patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
          - kind: ConfigMap
            name: drawio-values
            valuesKey: values.yaml
    target:
      kind: HelmRelease
      name: drawio