apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: default
resources:
  - ../../base/metube
configMapGenerator:
  - name: metube-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
patches:
  - patch: |-
      - op: add
        path: /spec/valuesFrom
        value:
          - kind: ConfigMap
            name: prod-metube-values
            valuesKey: values.yaml
    target:
      kind: HelmRelease
      name: metube