controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/alexta69/metube
          tag: "2026.06.13@sha256:b18205945425c24627344aa9ac7505d65314260be45b010f2324dd1cb2e9c73c"
    strategy: Recreate

ingress:
  main:
    className: traefik
    hosts:
    - host: metube.mistyfumes.dev
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: main
          port: http
    tls:
    - hosts:
      - metube.mistyfumes.dev
      secretName: prod-mistyfumes-tls

service:
  main:
    controller: main
    ports:
      http:
        port: 8081

configMaps:
  app-config:
    data:
      DELETE_FILE_ON_TRASHCAN: "true"

persistence:
  downloads:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: truenas-iscsi
    size: 10Gi
    globalMounts:
      - path: /downloads
