apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: termix-ssh
  namespace: default
spec:
  interval: 15m
  targetNamespace: default
  chart:
    spec:
      chart: ./kubernetes/services/termix-ssh/charts/termix-ssh
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: termix-ssh-values
      valuesKey: values.yaml
  install:
      remediation:
        retries: 5
  upgrade:
    remediation:
      retries: 5