---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ats-secrets
  namespace: default
spec:
  encryptedData:
    ETS_SERVER_LOGON_TOKEN: AgCEftGVmS6shve/DqiggnHC8q64Cn0bp6a29YRflZleymAI7iJKLaevXZ/nmiELidA+CTp6/LJcRZKmZ+/FURj1gqLuFOkmyTzgMRUyvT7wlVB3pgo6nQpfdC0xj4ZIs+nMyTQnLtLm7L1jVQQH/b8xXEGOogygdTBviMt4bb6VIwMmKmj21ld3sXzF93RsiAfSQQFKS8r4wsiLFSjYZHsKMo8KfjFJ6wqUGkgCVsTJFf+C0hXQSsXGaa3+zn/SEipUTy3/6dL9xX5DVHudUvW9DWk0CJ9irydjOzd4AdIDyX3CXIOjU5g3qe3B0oCaAjB2CG+bboDmdlIBztPOaWWDUv0zyY2dLd0OK13Lrx6O0UaTDf7+LJTojQMxdiXseinFVlBzxQcjGhwEEzfoM0AapnxtxkcOH1K+KFA8bR+WNhvB9srtvYBxLOCN+ay5vMtSfMAZX/myGi7FRXJOPyhIYjJk46qB8Elf3Ph+JN93/LwZmiIPVKj8E6gG6n+lkSQwD3zg5O0PAyWKpNrfpQc7lSzyKTOXnL3+X4T1IPX5JMPfcEenhULrLIb/hm+8Yp/qF9R5yYMLNwZ/ouWc9MdhhUVeWdz9jleuMwoJsYOPhWHWCqm+rNyEHttmpwYJ2148hQQloo/98tFsCEZCA2Vrj5awhrd2VV7CUfCVHeNKMlo5+69bXQzYMFV2Zm1z/DOaITNUyy+v5xrZhm+oL1ZyAIlWa0+bbK6iPPL2Yq+Npg==
    ETS_SERVER_MODERATORS: AgCtQqJtM5x0K2fIa2a7Knb1IGysIyR2brfDVxVXIjLixwxO7QrZc2cvPDtT9rrY8H3+gaiPMDymr5CoS+wPNltz+wh9hCvAKD0c6olaqr7HqtFF4YE47XdA12FQubYM5O11sJhDBj269L+GqEgpTyAuwHgzXHyv6pn+nLt4NqSaSMU+X8aTgfShQMmXEcKM1nCAWDiyAccFE4468FAvltBV7idFKGNtn7PyLBrXzOXyQ0WyhaVjMv+1qFzIUW/K7mxI+kKRKHMbwbUxYOtCU0Ry0TzrLYlYkX8Tp/AJ1DLyEaIXOszTBGxChg5i0QqBiv0uOdcAoSFmOKetlyYhAokDBVIFJ7y3qSJB2d9ek5wXBb/Gx6w5Mq+QpGA5Aopu5LRU6pM81ieEH7RK+vHgcFHcvYA/sFFz2oPLaiihYLq5JyYtPdRCSaMSTgf6hy2c0mfLNxSXzumBhgSsb0mbCu0hw12B1Qb+MNu2BbR31Gu4YiAEHNnUEzBqIRBkoVSKgtPPVAlgeKHG0VF5YhqNAgt0DmF5JFVbxcpHuMfccWFH/RhiOG9xBlzyyS/UkuBEWktGTKCoFlCoI+TvhGiKQ9DXi3J0zlVc05fNXd8tDHXEiJeJN5ZZQm/YBhMg+Vn9fpG3lHvvPXUKLNybn6k12UvTeQjykQKIeLnuNLiMq3+BCzRQr/GJOPzYx0kQThXmPgoX3wtnMlrH+wNOTlKTdCb3Ew==
  template:
    metadata:
      name: ats-secrets
      namespace: default
