apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: ./infrastructure/charts/metube
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom: []
  install:
      remediation:
        retries: 5
  upgrade:
    remediation:
      retries: 5