apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - authentik.yaml
  # - bytestash.yaml
  # - drawio.yaml
  # - homepage.yaml
  # - immich.yaml
  # - it-tools.yaml
  # - kaneo.yaml
  # - metube.yaml
  # - termix-ssh.yaml